apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - workspace-composition.yaml
  - application-composition.yaml
  - state-store-composition.yaml
  - event-stream-composition.yaml
