apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - workspace-composition.yaml
  - application-composition.yaml
  - infrastructure-composition.yaml
  - kafka-instance-composition.yaml
